### ISSUE TITLE
getting error to credentials please help me to fix it.

### ISSUE THREAD

**Issue by sumit1581** [sajidifti/Daanbaksho#1]
PS V:\MCA\Daanbaksho_Django\Daanbaksho_Django> python manage.py runserver
Traceback (most recent call last):
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\runserver.py", line 81, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
           ^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\conf\__init__.py", line 89, in __getattr__
    self._setup(name)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\conf\__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\conf\__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "V:\MCA\Daanbaksho_Django\Daanbaksho_Django\daanbaksho\settings.py", line 16, in <module> 
    from . import credentials
ImportError: cannot import name 'credentials' from 'daanbaksho' (V:\MCA\Daanbaksho_Django\Daanbaksho_Django\daanbaksho\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "V:\MCA\Daanbaksho_Django\Daanbaksho_Django\manage.py", line 22, in <module>
    main()
  File "V:\MCA\Daanbaksho_Django\Daanbaksho_Django\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 426, in run_from_argv
    connections.close_all()
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\connection.py", line 76, in all
    return [
           ^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\connection.py", line 73, in __iter__
    return iter(self.settings)
                ^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\conf\__init__.py", line 89, in __getattr__
    self._setup(name)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\conf\__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\conf\__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "V:\MCA\Daanbaksho_Django\Daanbaksho_Django\daanbaksho\settings.py", line 16, in <module> 
    from . import credentials
ImportError: cannot import name 'credentials' from 'daanbaksho' (V:\MCA\Daanbaksho_Django\Daanbaksho_Django\daanbaksho\__init__.py)

**Comment by sajidifti** [comment]
Create a file named credentials.py inside Daanbaksho_Django/daanbaksho/ folder (where settings.py is). The credentials file should contain your email credentials. Set credential variable names accordingly in settings.py.
